-- =============================================
-- createTables.sql - Beispiel-Tabellen für Db2 for i
-- Zweck: Erstellt Beispieltabellen (Sales, Orders, EAV) in Library YOUR_LIB
-- Hinweis: Ersetze YOUR_LIB durch deine Test-Library (SET SCHEMA)
-- Ausführung: db2 -t -f createTables.sql
-- =============================================

SET SCHEMA YOUR_LIB;

-- Create the AGENTS table with a primary key constraint
CREATE TABLE AGENTS (
   AGENT_CODE    VARCHAR(6)            NOT NULL,
   AGENT_NAME    VARCHAR(40)           NOT NULL,
   WORKING_AREA  VARCHAR(35)           NOT NULL,
   COMMISSION    DECIMAL(10, 2)        NOT NULL,
   PHONE_NO      VARCHAR(15)           NOT NULL,
   COUNTRY       VARCHAR(25)           NOT NULL,
   PRIMARY KEY (AGENT_CODE)
);

-- Create the CUSTOMERS table with primary key and foreign key constraints
CREATE TABLE CUSTOMERS (
   CUST_CODE        VARCHAR(6)          NOT NULL,
   CUST_NAME        VARCHAR(40)         NOT NULL,
   CUST_CITY        VARCHAR(35)         NOT NULL,
   WORKING_AREA     VARCHAR(35)         NOT NULL,
   CUST_COUNTRY     VARCHAR(20)         NOT NULL,
   GRADE            INTEGER             NOT NULL,
   OPENING_AMT      DECIMAL(12, 2)      NOT NULL,
   RECEIVE_AMT      DECIMAL(12, 2)      NOT NULL,
   PAYMENT_AMT      DECIMAL(12, 2)      NOT NULL,
   OUTSTANDING_AMT  DECIMAL(12, 2)      NOT NULL,
   PHONE_NO         VARCHAR(17)         NOT NULL,
   AGENT_CODE       VARCHAR(6)          NOT NULL,
   PRIMARY KEY (CUST_CODE),
   FOREIGN KEY (AGENT_CODE) REFERENCES AGENTS(AGENT_CODE)
);

-- Create the ORDERS table with primary key and foreign key constraints
CREATE TABLE ORDERS (
   ORD_NUM          DECIMAL(6)          NOT NULL,
   ORD_AMOUNT       DECIMAL(12, 2)      NOT NULL,
   ADVANCE_AMOUNT   DECIMAL(12, 2)      NOT NULL,
   ORD_DATE         DATE                NOT NULL,
   CUST_CODE        VARCHAR(6)          NOT NULL,
   AGENT_CODE       VARCHAR(6)          NOT NULL,
   ORD_DESCRIPTION  VARCHAR(90)         NOT NULL,
   PRIMARY KEY (ORD_NUM),
   FOREIGN KEY (CUST_CODE) REFERENCES CUSTOMERS(CUST_CODE),
   FOREIGN KEY (AGENT_CODE) REFERENCES AGENTS(AGENT_CODE)
);

-- Create the AGENT_REVENUE table with a primary key constraint
CREATE TABLE AGENT_REVENUE (
   AGENT_CODE          VARCHAR(6)        NOT NULL,
   AGENT_NAME          VARCHAR(40)       NOT NULL,
   CUMULATIVE_REVENUE  DECIMAL(12, 2)    NOT NULL,
   PRIMARY KEY (AGENT_CODE)
);

-- Create Entity Attribute Value (EAV) tables
CREATE TABLE EAV_DATA (
    ENTITY_ID VARCHAR(255) NOT NULL,
    ATTRIBUTE_KEY VARCHAR(255) NOT NULL,
    ATTRIBUTE_VALUE CLOB(1M) NOT NULL,
    PRIMARY KEY (ENTITY_ID, ATTRIBUTE_KEY)
);

CREATE INDEX IDX_ENTITY_ID ON EAV_DATA (ENTITY_ID);
CREATE INDEX IDX_ATTRIBUTE_KEY ON EAV_DATA (ATTRIBUTE_KEY);

CREATE TABLE EAV_METADATA (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ENTITY_ID VARCHAR(255) NOT NULL,
    METADATA_KEY VARCHAR(255) NOT NULL,
    METADATA_TYPE VARCHAR(255) NOT NULL,
    METADATA_VALUE CLOB(1M),
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_METADATA_KEY ON EAV_METADATA (METADATA_KEY);
CREATE INDEX IDX_METADATA_TYPE ON EAV_METADATA (METADATA_TYPE);
